version: 2.1

orbs:
  node: circleci/node@1.1.6
executors:
  node:
    docker:
      - image: cimg/node:16.14.2
    working_directory: /tmp/gatsby-plugin-s3

jobs:
  deploy-docs:
    working_directory: ~/project/docs
    executor:
      name: node
    steps:
      - checkout:
          path: ~/project
      - node/with-cache:
          steps:
            - run: npm ci
            - run:
                command: npm ci
                working_directory: ~/project/docs/.awesome
            - run: npm run build
            - run: npm run deploy
  install:
    working_directory: ~/project
    executor: node
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: npm-root
          command: 'npm ci --dev'
      - run:
          name: npm-projects
          command: 'npm exec -- lerna exec -- npm ci --dev'
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}-{{ checksum "examples/with-redirects/package-lock.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .
  lint:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: lint
          command: npm exec -- lerna run lint
      - store_artifacts:
          prefix: tests
          path: "./reports"
      - store_test_results:
          path: "./reports"

  build:
    executor: node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: build
          command: npm exec -- lerna run build
      - persist_to_workspace:
          root: .
          paths:
            - .
  test_e2e:
    executor: node
    environment:
      SKIP_BUCKET_CLEANUP: 1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: e2e-tests
          command: npm exec -- lerna run --scope gatsby-plugin-s3-e2e-tests test
          environment:
            JEST_JUNIT_OUTPUT: "../reports/e2e-test-results.xml"
      - store_artifacts:
          prefix: tests
          path: "./reports"
      - store_test_results:
          path: "./reports"

workflows:
  deploy-docs:
    jobs:
      - deploy-docs:
          context: gatsby-plugin-s3-docs
          filters:
            branches:
              only: master
  main:
    jobs:
      - install
      - lint:
          requires:
            - install
      - build:
          requires:
            - install
      - test_e2e:
          context: gatsby-plugin-s3-e2e
          requires:
            - build
